### ISSUE TITLE
Array items with multiply keys are not loaded properly

### ISSUE THREAD

**Issue by atorkhov** [h4evr/commonjs-javascript-yaml-parser#5]
```

---
list:
  - elem1:
      elem1_1: data1
    elem2: data2
```

`list` will become `Array` object with additional `elem2` property. I don't know how properly format it in JSON, but something like this:

```
{
  list: {
    0: { elem1: {elem1_1: "data1" } },
    elem2: "data2"
  }
}
```

I was expecting:

```
{
  list: [
    { elem1: { elem1_1: "data1" },
      elem2: "data2" }
  ]
}
```
